# Generated by Django 4.2.13 on 2026-08-11 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_expense_date'),
        ('estimates', '0008_fix_stable_key_and_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraBlockExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статья расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_expenses', to='projects.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Внесметный расход',
                'verbose_name_plural': 'Внесметные расходы',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
