# Generated by Django 4.2.13 on 2026-05-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: А, Б, В или Блок 1', max_length=100, verbose_name='Название блока')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, help_text='Общий бюджет, выделенный на блок', max_digits=15, verbose_name='Бюджет блока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название ЖК')),
                ('total_planned_cost', models.DecimalField(decimal_places=2, default=0, help_text='Ожидаемая выручка от продажи объекта', max_digits=15, verbose_name='Плановая стоимость реализации')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('construction', 'Строительство'), ('completed', 'Завершён'), ('frozen', 'Заморожен')], default='planning', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Жилой комплекс',
                'verbose_name_plural': 'Жилые комплексы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('planned_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Плановые расходы (смета)')),
                ('actual_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Фактические расходы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='residential_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.residentialcomplex', verbose_name='Жилой комплекс'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('residential_complex', 'name')},
        ),
    ]
