# Generated by Django 4.2.13 on 2026-05-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_excelimport_import_mode'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этажа')),
                ('name', models.CharField(blank=True, help_text='Необязательно. Например: "Цокольный", "Технический"', max_length=100, verbose_name='Название / описание')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название организации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(help_text='Например: А, Б, В или Секция 1', max_length=100, verbose_name='Название блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Бюджет блока'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая сдача'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='actual_expenses',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Используется только если этажи не добавлены', max_digits=15, verbose_name='Фактические расходы (вручную)'),
        ),
        migrations.CreateModel(
            name='FloorExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, help_text='Например: НФ-00000130', max_length=50, verbose_name='Код номенклатуры')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Единица измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена за единицу')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.floor', verbose_name='Этаж')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='imports.excelimport', verbose_name='Источник (импорт)')),
            ],
            options={
                'verbose_name': 'Расход этажа',
                'verbose_name_plural': 'Расходы этажа',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='projects.stage', verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complexes', to='projects.organization', verbose_name='Организация'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('stage', 'number')},
        ),
    ]
