# Generated by Django 4.2.13 on 2026-06-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_floor_organization_alter_block_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь (м²)'),
        ),
    ]
