# Generated by Django 4.2.13 on 2026-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_square_meters_to_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь (м²)'),
        ),
    ]
