# Generated by Django 4.2.13 on 2026-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_floorexpense_nomenclature'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorexpense',
            name='expense_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
    ]
