# Generated by Django 4.2.13 on 2026-08-13 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(default=1, verbose_name='Этаж')),
                ('apartment_number', models.CharField(max_length=100, verbose_name='Номер квартиры')),
                ('rooms', models.IntegerField(default=1, verbose_name='Количество комнат')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (м²)')),
                ('planned_price_per_m2', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Плановая цена м²')),
                ('fact_price_per_m2', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фактическая цена м²')),
                ('client_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО клиента')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('deal_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('deal_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('deal_amount_contract', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма договора')),
                ('deal_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Оплачено')),
                ('deal_amount_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Остаток к оплате')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Скидка')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продана')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Бронь')),
                ('is_barter', models.BooleanField(default=False, verbose_name='Бартер')),
                ('contract_type', models.CharField(blank=True, max_length=100, verbose_name='Тип сделки')),
                ('curator', models.CharField(blank=True, max_length=100, verbose_name='Куратор')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Файл-источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='projects.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['floor', 'apartment_number'],
                'unique_together': {('block', 'apartment_number')},
            },
        ),
    ]
