# Generated by Django 4.2.13 on 2026-09-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Аман Тюреркинов', max_length=200, verbose_name='Имя и фамилия')),
                ('position', models.CharField(default='Генеральный директор / CEO', max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='director/', verbose_name='Фото')),
                ('phone', models.CharField(blank=True, default='0558212040', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='amanturagency@gmail.com', max_length=254, verbose_name='Email')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('company', models.CharField(blank=True, default='Строй Финанс', max_length=200, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Директор / CEO',
                'verbose_name_plural': 'Директор / CEO',
            },
        ),
    ]
