# Generated by Django 4.2.13 on 2026-08-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('vehicle_name', models.CharField(max_length=300, verbose_name='Марка / описание авто')),
                ('source_text', models.CharField(blank=True, help_text='Заполняется при импорте если блок не распознан', max_length=200, verbose_name='Объект поступления (текст)')),
                ('amount_in', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Приход')),
                ('amount_out', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Расход')),
                ('counterparty', models.CharField(blank=True, max_length=300, verbose_name='Подрядчик / кому ушло')),
                ('target_text', models.CharField(blank=True, max_length=200, verbose_name='Объект расхода (текст)')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='За что / куда ушло')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Файл-источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_transactions', to='projects.organization', verbose_name='Компания')),
                ('source_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_source_transactions', to='projects.block', verbose_name='Объект поступления (блок)')),
                ('target_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_target_transactions', to='projects.block', verbose_name='Объект расхода (блок)')),
            ],
            options={
                'verbose_name': 'Операция склада авто',
                'verbose_name_plural': 'Операции склада авто',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
