# Generated by Django 4.2.13 on 2026-08-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimates', '0008_fix_stable_key_and_migrate_links'),
        ('projects', '0006_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('account_type', models.CharField(choices=[('cash', 'Касса'), ('bank', 'Банк')], default='cash', max_length=10, verbose_name='Тип')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_accounts', to='projects.residentialcomplex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Касса / счёт',
                'verbose_name_plural': 'Кассы / счета',
                'ordering': ['residential_complex__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DDSImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dds/%Y/%m/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершён'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('rows_total', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('rows_processed', models.IntegerField(default=0, verbose_name='Обработано')),
                ('rows_error', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('residential_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dds_imports', to='projects.residentialcomplex', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Импорт ДДС',
                'verbose_name_plural': 'Импорты ДДС',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name='Дата')),
                ('bank_or_cash', models.CharField(blank=True, max_length=50, verbose_name='Банк/Касса')),
                ('operation_type', models.CharField(max_length=100, verbose_name='Тип операции')),
                ('direction', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('transfer', 'Перемещение')], max_length=10, verbose_name='Направление')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма перемещения')),
                ('counterparty', models.CharField(blank=True, max_length=255, verbose_name='Контрагент')),
                ('account_name', models.CharField(blank=True, max_length=255, verbose_name='Счёт (1С)')),
                ('object_ref', models.CharField(blank=True, max_length=255, verbose_name='Объект (1С)')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Назначение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='dds.cashaccount', verbose_name='Касса')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dds_records', to='projects.block', verbose_name='Блок')),
                ('estimate_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dds_records', to='estimates.estimateitem', verbose_name='Позиция сметы')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='dds.ddsimport', verbose_name='Импорт')),
            ],
            options={
                'verbose_name': 'Запись ДДС',
                'verbose_name_plural': 'Записи ДДС',
                'ordering': ['-operation_date', '-created_at'],
            },
        ),
    ]
