# Generated by Django 4.2.13 on 2026-08-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_expense_date'),
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_accounts', to='projects.block', verbose_name='Блок'),
        ),
    ]
