# Generated by Django 4.2.13 on 2026-08-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_expense_date'),
        ('dds', '0002_add_block_to_cashaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsimport',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dds_imports', to='projects.block', verbose_name='Блок'),
        ),
    ]
