# Generated by Django 4.2.13 on 2026-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0003_add_block_to_ddsimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='description',
            field=models.TextField(blank=True, verbose_name='Назначение'),
        ),
    ]
