# Generated by Django 4.2.13 on 2026-09-04 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_expense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='Номер этажа')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='План кол-во')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План сумма')),
                ('fact_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Факт кол-во')),
                ('fact_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Факт сумма')),
                ('fact_date', models.DateField(blank=True, null=True, verbose_name='Дата факта')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Подрядчик')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_works', to='projects.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Работа по этажу',
                'verbose_name_plural': 'Работы по этажам',
                'ordering': ['floor_number', 'category__order'],
            },
        ),
        migrations.CreateModel(
            name='LandscapingWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='План кол-во')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План сумма')),
                ('fact_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Факт кол-во')),
                ('fact_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Факт сумма')),
                ('fact_date', models.DateField(blank=True, null=True, verbose_name='Дата факта')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Подрядчик')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landscaping_works', to='projects.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Работа по благоустройству',
                'verbose_name_plural': 'Работы по благоустройству',
                'ordering': ['category__order'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('unit', models.CharField(default='м²', max_length=20, verbose_name='Единица изм.')),
                ('scope', models.CharField(choices=[('floor', 'По этажам'), ('landscaping', 'Благоустройство'), ('general', 'Общее')], default='floor', max_length=20, verbose_name='Область')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Цвет (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_type', models.CharField(choices=[('avr', 'АВР — Акт выполненных работ'), ('asm', 'АСМ — Акт списанных материалов')], max_length=10, verbose_name='Тип акта')),
                ('act_number', models.CharField(max_length=50, verbose_name='Номер акта')),
                ('act_date', models.DateField(verbose_name='Дата акта')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Подрядчик')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итого')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_acts', to='projects.block', verbose_name='Блок')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_acts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('floor_works', models.ManyToManyField(blank=True, related_name='acts', to='planfact.floorwork', verbose_name='Работы по этажам')),
                ('landscaping_works', models.ManyToManyField(blank=True, related_name='acts', to='planfact.landscapingwork', verbose_name='Благоустройство')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'ordering': ['-act_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='landscapingwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landscaping_works', to='planfact.workcategory', verbose_name='Вид работ'),
        ),
        migrations.AddField(
            model_name='landscapingwork',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landscaping_updates', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AddField(
            model_name='floorwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_works', to='planfact.workcategory', verbose_name='Вид работ'),
        ),
        migrations.AddField(
            model_name='floorwork',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_work_updates', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.CreateModel(
            name='BlockFloorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_floors', models.PositiveIntegerField(default=1, verbose_name='Всего этажей')),
                ('underground_floors', models.PositiveIntegerField(default=0, verbose_name='Подземных этажей')),
                ('has_landscaping', models.BooleanField(default=True, verbose_name='Есть благоустройство')),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_config', to='projects.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Конфигурация этажей блока',
                'verbose_name_plural': 'Конфигурации этажей',
            },
        ),
        migrations.AlterUniqueTogether(
            name='landscapingwork',
            unique_together={('block', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='floorwork',
            unique_together={('block', 'floor_number', 'category')},
        ),
    ]
