# Generated by Django 4.2.13 on 2026-09-04 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_expense_date'),
        ('planfact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_year', models.IntegerField(verbose_name='Год начала')),
                ('start_month', models.IntegerField(verbose_name='Месяц начала')),
                ('end_year', models.IntegerField(verbose_name='Год окончания')),
                ('end_month', models.IntegerField(verbose_name='Месяц окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_plans', to='projects.block', verbose_name='Блок')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Календарный план',
                'verbose_name_plural': 'Календарные планы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Ед.изм.')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planfact.calendarplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarMonthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План сумма')),
                ('fact_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Факт сумма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_plans', to='planfact.calendartask', verbose_name='Задача')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_updates', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Помесячный план',
                'verbose_name_plural': 'Помесячные планы',
                'unique_together': {('task', 'year', 'month')},
            },
        ),
    ]
