# Generated by Django 4.2.13 on 2026-09-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_expense_date'),
        ('planfact', '0002_calendarplan_calendartask_calendarmonthplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='Номер этажа')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Плановый бюджет (сом)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_budgets', to='projects.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Бюджет этажа',
                'verbose_name_plural': 'Бюджеты этажей',
                'ordering': ['floor_number'],
                'unique_together': {('block', 'floor_number')},
            },
        ),
    ]
