# Generated by Django 4.2.13 on 2026-09-07 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_expense_date'),
        ('planfact', '0003_floorbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='Номер этажа')),
                ('doc_number', models.CharField(blank=True, max_length=50, verbose_name='Номер акта')),
                ('doc_date', models.DateField(verbose_name='Дата акта')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание (зона работ)')),
                ('head_warehouse', models.CharField(blank=True, max_length=200, verbose_name='Зав. склад')),
                ('head_section', models.CharField(blank=True, max_length=200, verbose_name='Нач. участка')),
                ('head_accounting', models.CharField(blank=True, max_length=200, verbose_name='Главный бухгалтер')),
                ('head_production', models.CharField(blank=True, max_length=200, verbose_name='Нач. производство')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asm_documents', to='projects.block', verbose_name='Блок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asm_documents', to='planfact.workcategory', verbose_name='Вид работ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asm_docs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'АСМ',
                'verbose_name_plural': 'АСМ — Акты списания материалов',
                'ordering': ['-doc_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsmItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование материала')),
                ('unit', models.CharField(max_length=30, verbose_name='Ед. измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед.')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planfact.asmdocument', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Строка АСМ',
                'verbose_name_plural': 'Строки АСМ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
