# Generated by Django 4.2.13 on 2026-09-08 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_expense_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planfact', '0005_blockaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvrDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(blank=True, null=True, verbose_name='Номер этажа')),
                ('doc_number', models.CharField(blank=True, max_length=50, verbose_name='Номер акта')),
                ('doc_date', models.DateField(verbose_name='Дата акта')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Подрядчик ИП')),
                ('executor', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель')),
                ('completion_pct', models.DecimalField(decimal_places=1, default=100, max_digits=5, verbose_name='% выполнения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выдан')], default='draft', max_length=10, verbose_name='Статус')),
                ('defects', models.CharField(blank=True, max_length=500, verbose_name='Выявленные недостатки')),
                ('defect_deadline', models.CharField(blank=True, max_length=200, verbose_name='Сроки устранения')),
                ('safety_compliance', models.CharField(blank=True, max_length=200, verbose_name='Соблюдение ТБ')),
                ('deadline_compliance', models.CharField(blank=True, max_length=200, verbose_name='Выполнение в сроки')),
                ('head_production', models.CharField(blank=True, max_length=200, verbose_name='Начальник производства')),
                ('head_section', models.CharField(blank=True, max_length=200, verbose_name='Начальник участка')),
                ('foreman', models.CharField(blank=True, max_length=200, verbose_name='Прораб')),
                ('master', models.CharField(blank=True, max_length=200, verbose_name='Мастер')),
                ('executor_sign', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель (подпись)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avr_documents', to='projects.block', verbose_name='Блок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avr_documents', to='planfact.workcategory', verbose_name='Вид работ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_avr_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'АВР',
                'verbose_name_plural': 'АВР — Акты выполненных работ',
                'ordering': ['-doc_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvrItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование работ')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Ед. измерения')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Кол-во')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planfact.avrdocument')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
