# Generated by Django 4.2.13 on 2026-09-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_expense_date'),
        ('planfact', '0006_avrdocument_avritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='Номер этажа')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_category_assignments', to='projects.block')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_assignments', to='planfact.workcategory')),
            ],
            options={
                'verbose_name': 'Виды работ по этажу',
                'verbose_name_plural': 'Виды работ по этажам',
                'ordering': ['floor_number', 'category__order'],
                'unique_together': {('block', 'floor_number', 'category')},
            },
        ),
    ]
