# Generated by Django 4.2.13 on 2026-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planfact', '0007_floor_category_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrdocument',
            name='accepted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма к оплате'),
        ),
        migrations.AddField(
            model_name='avrdocument',
            name='accepted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёмки'),
        ),
        migrations.AddField(
            model_name='avrdocument',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Принял'),
        ),
        migrations.AddField(
            model_name='avrdocument',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принято'),
        ),
    ]
