# Generated by Django 4.2.13 on 2026-09-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planfact', '0008_avr_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='avrdocument',
            name='is_rework',
            field=models.BooleanField(default=False, verbose_name='Переделка (не в смете)'),
        ),
    ]
