# Generated by Django 4.2.13 on 2026-09-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planfact', '0009_avr_rework'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvrPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avr_photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='planfact.avrdocument')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
