# Generated by Django 4.2.13 on 2026-10-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0009_add_extra_block_expense'),
        ('planfact', '0012_floorlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asmitem',
            name='estimate_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asm_items', to='estimates.estimateitem', verbose_name='Позиция сметы'),
        ),
    ]
