# Generated by Django 4.2.13 on 2026-05-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершён'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='Маппинг столбцов')),
                ('rows_total', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('rows_processed', models.IntegerField(default=0, verbose_name='Обработано')),
                ('rows_error', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Импорт Excel',
                'verbose_name_plural': 'Импорты Excel',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', 'Инфо'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=10, verbose_name='Тип')),
                ('row_number', models.IntegerField(blank=True, null=True, verbose_name='Номер строки')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='imports.excelimport', verbose_name='Импорт')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['created_at'],
            },
        ),
    ]
