# Generated by Django 4.2.13 on 2026-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimport',
            name='import_mode',
            field=models.CharField(choices=[('replace', 'Заменить существующие'), ('add', 'Суммировать с существующими')], default='replace', max_length=10, verbose_name='Режим импорта'),
        ),
    ]
