# Generated by Django 4.2.13 on 2026-05-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_excelimport_import_mode'),
        ('projects', '0002_floor_organization_alter_block_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelimport',
            name='target_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='projects.floor', verbose_name='Целевой этаж'),
        ),
    ]
